services:
  postgres-db:
    image: postgis/postgis:17-3.4
    container_name: meu_sintoma
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata: